### ISSUE TITLE
Warning with ruby 3

### ISSUE THREAD

**Issue by sebfie** [saiqulhaq/firebase_dynamic_link#4]
Hello,

I have this warning in ruby 3.0.3 : 

```
firebase_dynamic_link-1.0.4/lib/firebase_dynamic_link.rb:9:in `<top (required)>' [dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead
```

Thx

**Comment by saiqulhaq** [comment]
Hi @sebfie 
thanks for reporting

this PR https://github.com/saiqulhaq/firebase_dynamic_link/pull/5 will fix that issue

**Comment by saiqulhaq** [comment]
fixed https://rubygems.org/gems/firebase_dynamic_link/versions/1.0.5

**Comment by sebfie** [comment]
Thank you a lot

**Comment by avvari-da** [comment]
I don't think this is fixed. I still see it in `1.1.0`.
```
/usr/local/bundle/gems/firebase_dynamic_link-1.1.0/lib/firebase_dynamic_link.rb:11:in `<main>' [dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead
```
